include:

  - component: $CI_SERVER_FQDN/to-be-continuous/python/gitlab-ci-python@9.6.1
    inputs:
      dep-groups: "dev"
      pytest-enabled: true
      bandit-enabled: true
      bandit-args: "-c pyproject.toml --recursive ."

  - component: $CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@4.3.0
    inputs:
      changelog-enabled: true
      auto-release-enabled: true

  - component: $CI_SERVER_FQDN/usinelogicielle/public/gitlab-ci-components/sonarqube-component/sonarqube@1.3.2
    inputs:
      sq_users_admin: ${PDSSP_SONAR_USERS_ADMIN}
      sq_users_reader: ${TEAM_EMAIL}
      custom_args_sonar_scanner: >
        -Dsonar.gitlab.url=${CI_PROJECT_URL}
        -Dsonar.links.ci=${CI_PROJECT_URL}/pipelines
        -Dsonar.links.issue=${CI_PROJECT_URL}/-/issues
        -Dsonar.links.scm=${CI_PROJECT_URL}
        -Dsonar.projectBaseDir=${CI_PROJECT_DIR}
        -Dsonar.projectVersion=${PROJECT_VERSION}
        -Dsonar.profile=${PROJECT_QUALITY_PROFILE}
        -Dsonar.qualitygate.wait=true
        -Dsonar.qualitygate.timeout=300

stages:
  - build
  - test
  - package-build
  - package-test
  - sonarqube
  - deploy
  - acceptance
  - publish

default:
  tags:
    - Usine_Logicielle_Podman

variables:
  PIP_INDEX_URL: "https://${PDSSP_DEV_USERNAME}:${PDSSP_DEV_TOKEN}@${UL_ARTIFACTORY_HOST}/artifactory/api/pypi/pypi/simple"

  SONAR_TOKEN: ${PDSSP_SONAR_TOKEN}

sonarqube:
  needs:
    - py-pytest

# because we need git
.python-base:
  before_script:
    - !reference [.python-scripts]
    - install_ca_certs "${CUSTOM_CA_CERTS:-$DEFAULT_CA_CERTS}"
    - configure_netrc
    # Ignore cached files
    - mkdir -p .cache && echo "*" >> .cache/.gitignore
    - enforce_python_cmd
    - cd ${PYTHON_PROJECT_DIR}
    - guess_build_system
    - |
      if [[ "$PYTHON_BUILD_SYSTEM" =~ ^uv ]]; then
        trap "cleanup_uv_cache" EXIT
      fi
    - maybe_install_packages git build-essential

prepare_version:
  stage: test
  image: ${UL_ARTIFACTORY_HOST}/pdssp-docker/astral-sh/uv:python3.12-bookworm-slim
  retry: 2
  script:
    - PROJECT_VERSION=$(uv version | cut -d' ' -f2)
    - echo "PROJECT_VERSION=$PROJECT_VERSION" >> version.env
  artifacts:
    reports:
      dotenv: version.env

pages:
  extends: .python-base
  stage: publish
  retry: 2
  script:
    - install_requirements
    - apt-get update && apt-get install -y --no-install-recommends nodejs npm graphviz
    - npm config set cafile "${CNES_CERTIFICATE}"
    - make doc
    - mv site public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  artifacts:
    paths:
      - public
