# sources
sonar.sources=src

# Python report paths
#If you do not specify an output file, the scanner will look for report paths located under the default .coverage-reports/*coverage-*.xml.
sonar.python.xunit.reportPath=reports/TEST-pytests.xml
sonar.python.coverage.reportPaths=reports/py-coverage.cobertura.xml

# Fix python version
sonar.python.version=3.12

# Optional: encoding
sonar.sourceEncoding=UTF-8

# unique project identifier (required)
sonar.projectKey=CNES.UL:pdssp:pyadql

# project metadata
sonar.projectName=PyADQL

sources=pyadql

tests=tests
