# skeleton-python-binary -  Command-line tool that generates project templates based on predefined Python project template
# Copyright (C) 2024-2025 - Centre National d'Etudes Spatiales
# SPDX-License-Identifier: Apache-2.0
# Auto-generated by skeleton-python-binary
"""Project metadata."""

from importlib.metadata import metadata

pkg_metadata = metadata("pyadql")

__name_soft__ = pkg_metadata.get("name", "unknown")
__version__ = pkg_metadata.get("version", "0.0.0")
__title__ = pkg_metadata.get("name", "unknown")
__description__ = pkg_metadata.get("summary", "")
__url__ = pkg_metadata.get("homepage", "")
__author__ = pkg_metadata.get("authors", "unknown")
__author_email__ = pkg_metadata.get("author-email", "unknown")
__license__ = pkg_metadata.get("license", "")
__copyright__ = (
    "2026, Centre National d'Etudes Spatiales (Jean-Christophe Malapert for PDSSP)"
)
