# skeleton-python-binary -  Command-line tool that generates project templates based on predefined Python project template
# Copyright (C) 2024-2025 - Centre National d'Etudes Spatiales
# SPDX-License-Identifier: Apache-2.0
# Auto-generated by skeleton-python-binary
"""
Module to configure global application logging using Loguru.

This module provides a function to set up a global logger using the `loguru` library,
allowing customization of log levels, output destinations, and formatting options.
"""

import sys

from loguru import logger


def configure_logging(
    level="INFO",
    sink=None,
    colorize=True,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    **kwargs,
):
    """
    Configure a global loguru logger.

    """
    # Use None + resolve sys.stderr here, so we always get the CURRENT
    # sys.stderr (important for tests that capture/replace stderr).
    if sink is None:
        sink = sys.stderr
    logger.remove()
    logger.add(
        sys.stderr, level=level.upper(), colorize=colorize, format=format, **kwargs
    )
